networks:
  virtual_network:
    driver: bridge
services:
  backend:
    build: .
    env_file: .env_docker
    ports:
    - "8081:8080"
    depends_on:
    - redis
    networks:
    - virtual_network
  frontend:
    build: ./static
    ports:
    - "3000:6969"
    environment:
      BACKEND_URL: "http://localhost:8089/kanban"
      URL_PREFIX: "/kanban"
      # IMPORT_PREFIX: "kanban"
    depends_on:
    - backend
    networks:
    - virtual_network
  redis:
    image: redis:latest
    # ports:
    # - "6379:6379"
    networks:
    - virtual_network
  nginx:
    build: ./nginx
    restart: always
    ports:
    - "8089:80"
    depends_on:
    - backend
    - frontend
    networks:
    - virtual_network
  
