services:
  backend:
    build: .
    env_file: .env_docker
    ports:
    - "8081:8080"
    depends_on:
    - redis
  frontend:
    build: ./static
    ports:
    - "6969:6969"
    environment:
      BACKEND_URL: "http://nginx:80"
      # URL_PREFIX: "http://localhost:8089/kanban"
      # IMPORT_PREFIX: "kanban"
    depends_on:
    - backend
  redis:
    image: redis:latest
    ports:
    - "6379:6379"
  nginx:
    build: ./nginx
    restart: always
    ports:
    - "8089:80"
    depends_on:
    - backend
    - frontend
  
