networks:
  virtual_network:
    driver: bridge
services:
  backend:
    build: .
    env_file: env/.env_backend_des
    ports:
    - "8081:8080"
    depends_on:
    - redis
    networks:
    - virtual_network
  frontend:
    build: ./static
    ports:
    - "80:6969"
    - "433:8433"
    env_file: env/.env_frontend_des
    depends_on:
    - backend
    networks:
    - virtual_network
  redis:
    image: docker.io/library/redis:latest
    # ports:
    # - "6379:6379"
    networks:
    - virtual_network
  nginx:
    build: ./nginx
    restart: always
    ports:
    - "8089:80"
    depends_on:
    - backend
    - frontend
    networks:
    - virtual_network
  
